"""
Constants for use in the game
"""

SHIPS = "Ships"
SYSTEMS = "SolarSystems"
LOCATION = "Location"
STATUS = "Status"
HYPERLANES = "Hyperlanes"
STARS = "Stars"
PLANETS = "Planets"
NAME = "Name"
STATE = "State"
POLL = "Poll"
LIST = "List"
SHIP = "Ship"
MOVE = "Move"
OBSERVE = "Observe"
SUCCESS = "Success"
RESULT_OBJECT = "ResultObject"
X = "X"
Y = "Y"
TYPE = "Type"
SUBJECT = "Subject"
ACTION = "Action"
ARGUMENTS = "Arguments"
AWAITING = "Awaiting Command"
PLAYERS = "Players"
BEGIN = "Begin"
MESSAGE = "Message"
